# Generated by Django 2.2.7 on 2020-01-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_adminpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmodel',
            name='time',
            field=models.CharField(default='', max_length=30),
        ),
    ]
