# Generated by Django 2.2.7 on 2020-01-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=30)),
                ('rice', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('bosta', models.CharField(max_length=30)),
            ],
        ),
    ]
