# Generated by Django 2.2.7 on 2020-01-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addstock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmodel',
            old_name='customer',
            new_name='stockedby',
        ),
    ]
