# Generated by Django 2.2.7 on 2020-01-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addstock', '0002_auto_20200119_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='bosta',
            field=models.IntegerField(),
        ),
    ]
