# Generated by Django 2.2.7 on 2020-01-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addstock', '0004_totalstockmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='productsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
            ],
        ),
    ]
