# Generated by Django 2.2.7 on 2020-01-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addstock', '0005_productsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='productamount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='productbosta',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
