# Generated by Django 2.2.7 on 2020-01-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addstock', '0006_auto_20200120_0321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='totalStockModel',
        ),
    ]
