# Generated by Django 2.2.7 on 2020-01-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addstock', '0007_delete_totalstockmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodel',
            name='time',
            field=models.CharField(default='', max_length=30),
        ),
    ]
