# Generated by Django 2.2.7 on 2020-01-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addstock', '0008_stockmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='time',
            field=models.DateTimeField(default=''),
        ),
    ]
