# Generated by Django 2.2.7 on 2020-01-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addstock', '0009_auto_20200120_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellStockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=30)),
                ('rice', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('bosta', models.IntegerField()),
                ('time', models.DateTimeField(default='')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
