# Generated by Django 2.2.7 on 2020-01-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addstock', '0010_sellstockmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='remainingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('ramount', models.IntegerField(default=0)),
                ('rbosta', models.IntegerField(default=0)),
            ],
        ),
    ]
