# Generated by Django 2.2.7 on 2020-01-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addstock', '0011_remainingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainingmodel',
            name='product',
            field=models.CharField(default='', max_length=30),
        ),
    ]
